Explotic\FormationBundle\Entity\InterventionEntreprise:
    type: entity
    table: interventionentreprise
    repositoryClass: Explotic\FormationBundle\Entity\InterventionEntrepriseRepository
    manyToOne:
      module:
        targetEntity: Module
        inversedBy: InterventionEntreprises
    fields:
      stade:
        type: string
        length: 255
    lifecycleCallbacks: {  }
